Creating a dataframe

In [6]:
import pandas as pd
df1=pd.read_csv(r'/Users/algo trading 2025/batch 30 hindi/9_data_analysis/sp500.csv')
df1

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [3]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df1=pd.DataFrame(stock)
df1

name  price sector
0  apple    300   tech
1   ongc    500    oil
2  artil    400    oil

In [6]:
stock={
    'name':['aapl','ongc','artil','tsla'],
    'price':['300','500','900','200'],
    'sector':['tech','oil','telecom','vehi']
}
df2=pd.DataFrame(stock)
df2

name price   sector
0   aapl   300     tech
1   ongc   500      oil
2  artil   900  telecom
3   tsla   200     vehi

In [8]:

data=[ [7 ,6, 3, 0],[8, 1, 2, 0],[9 ,4 ,9 ,5],[8, 6, 7 ,6] ]
print(data)
df = pd.DataFrame(
  data,
  index = ["a","b","c","d"],
  columns = ["col_a","col_b","col_c","col_d"]
  )

print(df)

[[7, 6, 3, 0], [8, 1, 2, 0], [9, 4, 9, 5], [8, 6, 7, 6]]
   col_a  col_b  col_c  col_d
a      7      6      3      0
b      8      1      2      0
c      9      4      9      5
d      8      6      7      6


In [9]:
import numpy as np
data=np.random.randint(10, size=(4,4))
print(data)
df = pd.DataFrame(
  data,
  index = ["a","b","c","d"],
  columns = ["col_a","col_b","col_c","col_d"]
  )

print(df)

[[8 3 8 5]
 [1 4 7 2]
 [6 7 2 4]
 [8 8 2 2]]
   col_a  col_b  col_c  col_d
a      8      3      8      5
b      1      4      7      2
c      6      7      2      4
d      8      8      2      2


In [7]:
pd.read_excel(r'/Users/algo trading 2025/batch 30 hindi/9_data_analysis/sample1.xlsx')

Apple Inc  Information Technology  170.12    9.2
0                      Abbvie Inc             Health Care   93.29   5.31
1             Abbott Laboratories             Health Care   55.28   2.41
2                   Accenture Plc  Information Technology  145.30   5.91
3                    Allergan Plc             Health Care  171.81  15.42
4    American International Group              Financials   59.50   2.51
..                            ...                     ...     ...    ...
96     Verizon Communications Inc      Telecommunications   45.85   3.75
97       Walgreens Boots Alliance        Consumer Staples   70.25   5.10
98          Wells Fargo & Company              Financials   54.02   4.14
99                Wal-Mart Stores        Consumer Staples   96.08   4.36
100              Exxon Mobil Corp                  Energy   80.31   3.56

[101 rows x 4 columns]

In [ ]:
import os
import certifi
os.environ['SSL_CERT_FILE'] = certifi.where()

import pandas as pd
pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]

Company name      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                  Bharat Petroleum        BPCL   
10                    Bharti Airtel  BHARTIARTL   
11             Britannia Industries   BRITANNIA   
12                            Cipla       CIPLA   
13                       Coal India   COALINDIA   
14         Dr. Reddy's Laboratories     DRREDDY   
15                    Eicher Motors   EICHERMOT   
16                Grasim Industries      GRASIM   
17                          HCLTech     HCLTECH   
18                        HDFC Bank    HDFCBANK   
19                        HDFC Life    HDFCLIFE   
20                    Hero MotoCorp  HEROMOTOCO   
21              Hindalco Industries    HINDALCO   
22               Hindustan Unilever  HINDUNILVR   
23                       ICICI Bank   ICICIBANK   
24                    IndusInd Bank  INDUSINDBK   
25                          Infosys        INFY   
26                              ITC         ITC   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                        Sector[15]        Date added[16]  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9      Oil, Gas & Consumable Fuels    28 October 2002[c]  
10               Telecommunication          1 March 2004  
11      Fast Moving Consumer Goods      29 March 2019[d]  
12                      Healthcare        7 October 1998  
13     Oil, Gas & Consumable Fuels       10 October 2011  
14                      Healthcare     1 October 2010[e]  
15  Automobile and Auto Components          1 April 2016  
16          Construction Materials       2 April 2018[f]  
17          Information Technology       28 October 2002  
18              Financial Services         22 April 1996  
19              Financial Services          31 July 2020  
20  Automobile and Auto Components     7 October 1998[g]  
21                 Metals & Mining         22 April 1996  
22      Fast Moving Consumer Goods         22 April 1996  
23   

In [ ]:
# !pip install openpyxl
# !pip freeze
# !pip install lxml
# !pip install certifi

  Using cached lxml-5.3.1-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.7 kB)
Using cached lxml-5.3.1-cp312-cp312-macosx_10_9_universal2.whl (8.2 MB)
