## Creating a dataframe

In [4]:
import pandas as pd
df11=pd.read_csv(r'/Users/algo trading 2025/batch 30 hindi/9_data_analysis/sp500.csv')
df11

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [3]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df1=pd.DataFrame(stock)
df1

name  price sector
0  apple    300   tech
1   ongc    500    oil
2  artil    400    oil

In [6]:
stock={
    'name':['aapl','ongc','artil','tsla'],
    'price':['300','500','900','200'],
    'sector':['tech','oil','telecom','vehi']
}
df2=pd.DataFrame(stock)
df2

name price   sector
0   aapl   300     tech
1   ongc   500      oil
2  artil   900  telecom
3   tsla   200     vehi

In [8]:

data=[ [7 ,6, 3, 0],[8, 1, 2, 0],[9 ,4 ,9 ,5],[8, 6, 7 ,6] ]
print(data)
df = pd.DataFrame(
  data,
  index = ["a","b","c","d"],
  columns = ["col_a","col_b","col_c","col_d"]
  )

print(df)

[[7, 6, 3, 0], [8, 1, 2, 0], [9, 4, 9, 5], [8, 6, 7, 6]]
   col_a  col_b  col_c  col_d
a      7      6      3      0
b      8      1      2      0
c      9      4      9      5
d      8      6      7      6


In [9]:
import numpy as np
data=np.random.randint(10, size=(4,4))
print(data)
df = pd.DataFrame(
  data,
  index = ["a","b","c","d"],
  columns = ["col_a","col_b","col_c","col_d"]
  )

print(df)

[[8 3 8 5]
 [1 4 7 2]
 [6 7 2 4]
 [8 8 2 2]]
   col_a  col_b  col_c  col_d
a      8      3      8      5
b      1      4      7      2
c      6      7      2      4
d      8      8      2      2


In [5]:
df12=pd.read_excel(r'/Users/algo trading 2025/batch 30 hindi/9_data_analysis/sample1.xlsx')
df12

Apple Inc  Information Technology  170.12    9.2
0                      Abbvie Inc             Health Care   93.29   5.31
1             Abbott Laboratories             Health Care   55.28   2.41
2                   Accenture Plc  Information Technology  145.30   5.91
3                    Allergan Plc             Health Care  171.81  15.42
4    American International Group              Financials   59.50   2.51
..                            ...                     ...     ...    ...
96     Verizon Communications Inc      Telecommunications   45.85   3.75
97       Walgreens Boots Alliance        Consumer Staples   70.25   5.10
98          Wells Fargo & Company              Financials   54.02   4.14
99                Wal-Mart Stores        Consumer Staples   96.08   4.36
100              Exxon Mobil Corp                  Energy   80.31   3.56

[101 rows x 4 columns]

In [6]:
import os
import certifi
os.environ['SSL_CERT_FILE'] = certifi.where()

import pandas as pd
df13=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]

In [ ]:
# !pip install openpyxl
# !pip freeze
# !pip install lxml
# !pip install certifi

  Using cached lxml-5.3.1-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.7 kB)
Using cached lxml-5.3.1-cp312-cp312-macosx_10_9_universal2.whl (8.2 MB)


## method and attributes

In [17]:
df11.head(10)

Name                  Sector    Price    EPS
0                     Apple Inc  Information Technology   170.12   9.20
1                    Abbvie Inc             Health Care    93.29   5.31
2           Abbott Laboratories             Health Care    55.28   2.41
3                 Accenture Plc  Information Technology   145.30   5.91
4                  Allergan Plc             Health Care   171.81  15.42
5  American International Group              Financials    59.50   2.51
6                 Allstate Corp              Financials   100.50   6.79
7                         Amgen             Health Care   168.93  12.58
8               Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
9      American Express Company              Financials    93.92   5.22

In [18]:
df11.tail(10)

Name                  Sector   Price   EPS
92           Union Pacific Corp             Industrials  115.58  5.66
93        United Parcel Service             Industrials  113.20  5.98
94                 U.S. Bancorp              Financials   51.88  3.37
95     United Technologies Corp             Industrials  117.05  6.62
96                     Visa Inc  Information Technology  110.27  3.48
97   Verizon Communications Inc      Telecommunications   45.85  3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25  5.10
99        Wells Fargo & Company              Financials   54.02  4.14
100             Wal-Mart Stores        Consumer Staples   96.08  4.36
101            Exxon Mobil Corp                  Energy   80.31  3.56

In [19]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    102 non-null    object 
 1   Sector  102 non-null    object 
 2   Price   102 non-null    float64
 3   EPS     102 non-null    float64
dtypes: float64(2), object(2)
memory usage: 3.3+ KB


In [20]:
df11.describe()

Price         EPS
count   102.000000  102.000000
mean    150.500686    6.485294
std     240.768463    8.577741
min      12.110000    0.020000
25%      54.335000    2.885000
50%      88.295000    4.405000
75%     151.032500    6.565000
max    1762.230000   74.450000

In [22]:
df11.index

RangeIndex(start=0, stop=102, step=1)

In [23]:
df11.columns

Index(['Name', 'Sector', 'Price', 'EPS'], dtype='object')

In [24]:
df11.shape

(102, 4)

## subsetting

In [36]:
df13.Symbol

0       ADANIENT
1     ADANIPORTS
2     APOLLOHOSP
3     ASIANPAINT
4       AXISBANK
5     BAJAJ-AUTO
6     BAJFINANCE
7     BAJAJFINSV
8            BEL
9           BPCL
10    BHARTIARTL
11     BRITANNIA
12         CIPLA
13     COALINDIA
14       DRREDDY
15     EICHERMOT
16        GRASIM
17       HCLTECH
18      HDFCBANK
19      HDFCLIFE
20    HEROMOTOCO
21      HINDALCO
22    HINDUNILVR
23     ICICIBANK
24    INDUSINDBK
25          INFY
26           ITC
27      JSWSTEEL
28     KOTAKBANK
29            LT
30           M&M
31        MARUTI
32     NESTLEIND
33          NTPC
34          ONGC
35     POWERGRID
36      RELIANCE
37       SBILIFE
38    SHRIRAMFIN
39          SBIN
40     SUNPHARMA
41           TCS
42    TATACONSUM
43    TATAMOTORS
44     TATASTEEL
45         TECHM
46         TITAN
47         TRENT
48    ULTRACEMCO
49         WIPRO
Name: Symbol, dtype: object

In [37]:
df13['Symbol']

0       ADANIENT
1     ADANIPORTS
2     APOLLOHOSP
3     ASIANPAINT
4       AXISBANK
5     BAJAJ-AUTO
6     BAJFINANCE
7     BAJAJFINSV
8            BEL
9           BPCL
10    BHARTIARTL
11     BRITANNIA
12         CIPLA
13     COALINDIA
14       DRREDDY
15     EICHERMOT
16        GRASIM
17       HCLTECH
18      HDFCBANK
19      HDFCLIFE
20    HEROMOTOCO
21      HINDALCO
22    HINDUNILVR
23     ICICIBANK
24    INDUSINDBK
25          INFY
26           ITC
27      JSWSTEEL
28     KOTAKBANK
29            LT
30           M&M
31        MARUTI
32     NESTLEIND
33          NTPC
34          ONGC
35     POWERGRID
36      RELIANCE
37       SBILIFE
38    SHRIRAMFIN
39          SBIN
40     SUNPHARMA
41           TCS
42    TATACONSUM
43    TATAMOTORS
44     TATASTEEL
45         TECHM
46         TITAN
47         TRENT
48    ULTRACEMCO
49         WIPRO
Name: Symbol, dtype: object

In [41]:
df13[['Company name','Symbol']]

Company name      Symbol
0                 Adani Enterprises    ADANIENT
1                 Adani Ports & SEZ  ADANIPORTS
2                  Apollo Hospitals  APOLLOHOSP
3                      Asian Paints  ASIANPAINT
4                         Axis Bank    AXISBANK
5                        Bajaj Auto  BAJAJ-AUTO
6                     Bajaj Finance  BAJFINANCE
7                     Bajaj Finserv  BAJAJFINSV
8                Bharat Electronics         BEL
9                  Bharat Petroleum        BPCL
10                    Bharti Airtel  BHARTIARTL
11             Britannia Industries   BRITANNIA
12                            Cipla       CIPLA
13                       Coal India   COALINDIA
14         Dr. Reddy's Laboratories     DRREDDY
15                    Eicher Motors   EICHERMOT
16                Grasim Industries      GRASIM
17                          HCLTech     HCLTECH
18                        HDFC Bank    HDFCBANK
19                        HDFC Life    HDFCLIFE
20                    Hero MotoCorp  HEROMOTOCO
21              Hindalco Industries    HINDALCO
22               Hindustan Unilever  HINDUNILVR
23                       ICICI Bank   ICICIBANK
24                    IndusInd Bank  INDUSINDBK
25                          Infosys        INFY
26                              ITC         ITC
27                        JSW Steel    JSWSTEEL
28              Kotak Mahindra Bank   KOTAKBANK
29                  Larsen & Toubro          LT
30              Mahindra & Mahindra         M&M
31                    Maruti Suzuki      MARUTI
32                     Nestlé India   NESTLEIND
33                             NTPC        NTPC
34  Oil and Natural Gas Corporation        ONGC
35                       Power Grid   POWERGRID
36              Reliance Industries    RELIANCE
37       SBI Life Insurance Company     SBILIFE
38                  Shriram Finance  SHRIRAMFIN
39              State Bank of India        SBIN
40                       Sun Pharma   SUNPHARMA
41        Tata Consultancy Services         TCS
42           Tata Consumer Products  TATACONSUM
43                      Tata Motors  TATAMOTORS
44                       Tata Steel   TATASTEEL
45                    Tech Mahindra       TECHM
46                    Titan Company       TITAN
47                            Trent       TRENT
48                 UltraTech Cement  ULTRACEMCO
49                            Wipro       WIPRO

## filter data

In [48]:
df11[df11['Price']>1000]

Name                  Sector    Price    EPS
8    Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
44  Alphabet Class C  Information Technology  1018.48  29.87
45  Alphabet Class A  Information Technology  1034.09  29.87
75   Priceline Group  Consumer Discretionary  1762.23  74.45

In [51]:
df11[df11['Sector']=='Information Technology']

Name                  Sector    Price    EPS
0                         Apple Inc  Information Technology   170.12   9.20
3                     Accenture Plc  Information Technology   145.30   5.91
26                Cisco Systems Inc  Information Technology    36.38   2.17
36                     Facebook Inc  Information Technology   179.14   5.19
44                 Alphabet Class C  Information Technology  1018.48  29.87
45                 Alphabet Class A  Information Technology  1034.09  29.87
50  International Business Machines  Information Technology   151.40  13.66
51                       Intel Corp  Information Technology    44.88   3.18
60                   Mastercard Inc  Information Technology   149.93   4.31
70                   Microsoft Corp  Information Technology    82.49   3.38
73                      Oracle Corp  Information Technology    48.97   2.55
80                  Paypal Holdings  Information Technology    76.55   1.40
81                     Qualcomm Inc  Information Technology    66.83   3.78
90                Texas Instruments  Information Technology    98.59   4.06
96                         Visa Inc  Information Technology   110.27   3.48

In [52]:
df11[(df11['Sector']=='Information Technology') & (df11['EPS']<10)]

Name                  Sector   Price   EPS
0           Apple Inc  Information Technology  170.12  9.20
3       Accenture Plc  Information Technology  145.30  5.91
26  Cisco Systems Inc  Information Technology   36.38  2.17
36       Facebook Inc  Information Technology  179.14  5.19
51         Intel Corp  Information Technology   44.88  3.18
60     Mastercard Inc  Information Technology  149.93  4.31
70     Microsoft Corp  Information Technology   82.49  3.38
73        Oracle Corp  Information Technology   48.97  2.55
80    Paypal Holdings  Information Technology   76.55  1.40
81       Qualcomm Inc  Information Technology   66.83  3.78
90  Texas Instruments  Information Technology   98.59  4.06
96           Visa Inc  Information Technology  110.27  3.48

In [54]:
df11['EPS']

0       9.20
1       5.31
2       2.41
3       5.91
4      15.42
       ...  
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

when you have a single column its called series